project_id = "kjjkvevplfkceiwwnfnn"

[functions.google-autocomplete]
verify_jwt = false

[functions.google-nearby-search]
verify_jwt = false

[functions.google-place-details]
verify_jwt = false

[functions.enrich-businesses]
verify_jwt = false

[functions.generate-partner-guide]
verify_jwt = false

[functions.normalize-business-name]
verify_jwt = false