// Types d'activités basés sur Google Places API v1 Table A
export interface BusinessType {
  id: string;
  label: string;
  googleSearchKeyword: string;
}

// Fonction utilitaire pour normaliser les chaînes (enlever les accents)
export const normalizeString = (str: string): string => {
  return str
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
};

// Option spéciale pour "Tous les types"
export const ALL_TYPES_OPTION: BusinessType = {
  id: "all",
  label: "Tout type d'activités",
  googleSearchKeyword: "",
};

// Liste complète des types Google Places API v1 (Table A)
// Triée par ordre alphabétique et filtrée
export const BUSINESS_TYPES: BusinessType[] = [
  { id: "accounting", label: "Comptable", googleSearchKeyword: "Comptable" },
  { id: "amusement_center", label: "Centre de loisirs", googleSearchKeyword: "Centre de loisirs" },
  { id: "amusement_park", label: "Parc d'attractions", googleSearchKeyword: "Parc d'attractions" },
  { id: "animal_shelter", label: "Refuge pour animaux", googleSearchKeyword: "Refuge pour animaux" },
  { id: "aquarium", label: "Aquarium", googleSearchKeyword: "Aquarium" },
  { id: "athletic_field", label: "Terrain de sport", googleSearchKeyword: "Terrain de sport" },
  { id: "atm", label: "Distributeur automatique", googleSearchKeyword: "Distributeur automatique" },
  { id: "bakery", label: "Boulangerie", googleSearchKeyword: "Boulangerie" },
  { id: "bank", label: "Banque", googleSearchKeyword: "Banque" },
  { id: "banquet_hall", label: "Salle de banquet", googleSearchKeyword: "Salle de banquet" },
  { id: "bar", label: "Bar", googleSearchKeyword: "Bar" },
  { id: "barbecue_restaurant", label: "Restaurant barbecue", googleSearchKeyword: "Restaurant barbecue" },
  { id: "beauty_salon", label: "Salon de beauté", googleSearchKeyword: "Salon de beauté" },
  { id: "bed_and_breakfast", label: "Chambre d'hôtes", googleSearchKeyword: "Chambre d'hôtes" },
  { id: "bicycle_store", label: "Magasin de vélos", googleSearchKeyword: "Magasin de vélos" },
  { id: "boat_dealer", label: "Concessionnaire de bateaux", googleSearchKeyword: "Concessionnaire de bateaux" },
  { id: "boat_rental", label: "Location de bateaux", googleSearchKeyword: "Location de bateaux" },
  { id: "book_store", label: "Librairie", googleSearchKeyword: "Librairie" },
  { id: "bowling_alley", label: "Bowling", googleSearchKeyword: "Bowling" },
  { id: "brazilian_restaurant", label: "Restaurant brésilien", googleSearchKeyword: "Restaurant brésilien" },
  { id: "breakfast_restaurant", label: "Restaurant petit-déjeuner", googleSearchKeyword: "Restaurant petit-déjeuner" },
  { id: "brunch_restaurant", label: "Restaurant brunch", googleSearchKeyword: "Restaurant brunch" },
  { id: "cafe", label: "Café", googleSearchKeyword: "Café" },
  { id: "campground", label: "Camping", googleSearchKeyword: "Camping" },
  { id: "car_dealer", label: "Concessionnaire automobile", googleSearchKeyword: "Concessionnaire automobile" },
  { id: "car_rental", label: "Location de voitures", googleSearchKeyword: "Location de voitures" },
  { id: "car_repair", label: "Garage automobile", googleSearchKeyword: "Garage automobile" },
  { id: "car_wash", label: "Lave-auto", googleSearchKeyword: "Lave-auto" },
  { id: "casino", label: "Casino", googleSearchKeyword: "Casino" },
  { id: "cell_phone_store", label: "Boutique de téléphones", googleSearchKeyword: "Boutique de téléphones" },
  { id: "cemetery", label: "Cimetière", googleSearchKeyword: "Cimetière" },
  { id: "child_care_agency", label: "Agence de garde d'enfants", googleSearchKeyword: "Agence de garde d'enfants" },
  { id: "chinese_restaurant", label: "Restaurant chinois", googleSearchKeyword: "Restaurant chinois" },
  { id: "clothing_store", label: "Magasin de vêtements", googleSearchKeyword: "Magasin de vêtements" },
  { id: "coffee_shop", label: "Café", googleSearchKeyword: "Café" },
  { id: "community_college", label: "Collège communautaire", googleSearchKeyword: "Collège communautaire" },
  { id: "convention_center", label: "Centre de congrès", googleSearchKeyword: "Centre de congrès" },
  { id: "convenience_store", label: "Épicerie", googleSearchKeyword: "Épicerie" },
  { id: "country_club", label: "Country club", googleSearchKeyword: "Country club" },
  { id: "day_care", label: "Crèche", googleSearchKeyword: "Crèche" },
  { id: "dentist", label: "Dentiste", googleSearchKeyword: "Dentiste" },
  { id: "department_store", label: "Grand magasin", googleSearchKeyword: "Grand magasin" },
  { id: "discount_store", label: "Magasin discount", googleSearchKeyword: "Magasin discount" },
  { id: "doctor", label: "Médecin", googleSearchKeyword: "Médecin" },
  { id: "drugstore", label: "Pharmacie", googleSearchKeyword: "Pharmacie" },
  { id: "dry_cleaning", label: "Pressing", googleSearchKeyword: "Pressing" },
  { id: "electric_vehicle_charging_station", label: "Borne de recharge électrique", googleSearchKeyword: "Borne de recharge électrique" },
  { id: "electrician", label: "Électricien", googleSearchKeyword: "Électricien" },
  { id: "electronics_store", label: "Magasin d'électronique", googleSearchKeyword: "Magasin d'électronique" },
  { id: "elementary_school", label: "École primaire", googleSearchKeyword: "École primaire" },
  { id: "event_venue", label: "Salle d'événements", googleSearchKeyword: "Salle d'événements" },
  { id: "extended_stay_hotel", label: "Hôtel longue durée", googleSearchKeyword: "Hôtel longue durée" },
  { id: "farm", label: "Ferme", googleSearchKeyword: "Ferme" },
  { id: "fast_food_restaurant", label: "Fast-food", googleSearchKeyword: "Fast-food" },
  { id: "fitness_center", label: "Centre de fitness", googleSearchKeyword: "Centre de fitness" },
  { id: "florist", label: "Fleuriste", googleSearchKeyword: "Fleuriste" },
  { id: "french_restaurant", label: "Restaurant français", googleSearchKeyword: "Restaurant français" },
  { id: "funeral_home", label: "Pompes funèbres", googleSearchKeyword: "Pompes funèbres" },
  { id: "furniture_store", label: "Magasin de meubles", googleSearchKeyword: "Magasin de meubles" },
  { id: "gas_station", label: "Station-service", googleSearchKeyword: "Station-service" },
  { id: "golf_course", label: "Terrain de golf", googleSearchKeyword: "Terrain de golf" },
  { id: "greek_restaurant", label: "Restaurant grec", googleSearchKeyword: "Restaurant grec" },
  { id: "grocery_store", label: "Épicerie", googleSearchKeyword: "Épicerie" },
  { id: "guest_house", label: "Maison d'hôtes", googleSearchKeyword: "Maison d'hôtes" },
  { id: "gym", label: "Salle de sport", googleSearchKeyword: "Salle de sport" },
  { id: "hair_care", label: "Coiffeur", googleSearchKeyword: "Coiffeur" },
  { id: "hair_salon", label: "Salon de coiffure", googleSearchKeyword: "Salon de coiffure" },
  { id: "hamburger_restaurant", label: "Restaurant hamburgers", googleSearchKeyword: "Restaurant hamburgers" },
  { id: "hardware_store", label: "Quincaillerie", googleSearchKeyword: "Quincaillerie" },
  { id: "health_spa", label: "Spa santé", googleSearchKeyword: "Spa santé" },
  { id: "high_school", label: "Lycée", googleSearchKeyword: "Lycée" },
  { id: "hiking_area", label: "Zone de randonnée", googleSearchKeyword: "Zone de randonnée" },
  { id: "home_goods_store", label: "Magasin d'articles pour la maison", googleSearchKeyword: "Magasin d'articles pour la maison" },
  { id: "home_improvement_store", label: "Magasin de bricolage", googleSearchKeyword: "Magasin de bricolage" },
  { id: "hospital", label: "Hôpital", googleSearchKeyword: "Hôpital" },
  { id: "hostel", label: "Auberge de jeunesse", googleSearchKeyword: "Auberge de jeunesse" },
  { id: "hotel", label: "Hôtel", googleSearchKeyword: "Hôtel" },
  { id: "ice_cream_shop", label: "Glacier", googleSearchKeyword: "Glacier" },
  { id: "indian_restaurant", label: "Restaurant indien", googleSearchKeyword: "Restaurant indien" },
  { id: "indonesian_restaurant", label: "Restaurant indonésien", googleSearchKeyword: "Restaurant indonésien" },
  { id: "insurance_agency", label: "Agence d'assurance", googleSearchKeyword: "Agence d'assurance" },
  { id: "italian_restaurant", label: "Restaurant italien", googleSearchKeyword: "Restaurant italien" },
  { id: "japanese_restaurant", label: "Restaurant japonais", googleSearchKeyword: "Restaurant japonais" },
  { id: "jewelry_store", label: "Bijouterie", googleSearchKeyword: "Bijouterie" },
  { id: "korean_restaurant", label: "Restaurant coréen", googleSearchKeyword: "Restaurant coréen" },
  { id: "laundry", label: "Blanchisserie", googleSearchKeyword: "Blanchisserie" },
  { id: "lawyer", label: "Avocat", googleSearchKeyword: "Avocat" },
  { id: "library", label: "Bibliothèque", googleSearchKeyword: "Bibliothèque" },
  { id: "liquor_store", label: "Magasin de spiritueux", googleSearchKeyword: "Magasin de spiritueux" },
  { id: "locksmith", label: "Serrurier", googleSearchKeyword: "Serrurier" },
  { id: "lodging", label: "Hébergement", googleSearchKeyword: "Hébergement" },
  { id: "meal_delivery", label: "Livraison de repas", googleSearchKeyword: "Livraison de repas" },
  { id: "meal_takeaway", label: "Plats à emporter", googleSearchKeyword: "Plats à emporter" },
  { id: "mediterranean_restaurant", label: "Restaurant méditerranéen", googleSearchKeyword: "Restaurant méditerranéen" },
  { id: "mexican_restaurant", label: "Restaurant mexicain", googleSearchKeyword: "Restaurant mexicain" },
  { id: "middle_eastern_restaurant", label: "Restaurant du Moyen-Orient", googleSearchKeyword: "Restaurant du Moyen-Orient" },
  { id: "middle_school", label: "Collège", googleSearchKeyword: "Collège" },
  { id: "motel", label: "Motel", googleSearchKeyword: "Motel" },
  { id: "motorcycle_dealer", label: "Concessionnaire de motos", googleSearchKeyword: "Concessionnaire de motos" },
  { id: "motorcycle_repair_shop", label: "Garage moto", googleSearchKeyword: "Garage moto" },
  { id: "movie_rental", label: "Location de films", googleSearchKeyword: "Location de films" },
  { id: "movie_theater", label: "Cinéma", googleSearchKeyword: "Cinéma" },
  { id: "moving_company", label: "Déménageur", googleSearchKeyword: "Déménageur" },
  { id: "nail_salon", label: "Salon de manucure", googleSearchKeyword: "Salon de manucure" },
  { id: "national_park", label: "Parc national", googleSearchKeyword: "Parc national" },
  { id: "night_club", label: "Boîte de nuit", googleSearchKeyword: "Boîte de nuit" },
  { id: "painter", label: "Peintre", googleSearchKeyword: "Peintre" },
  { id: "park", label: "Parc", googleSearchKeyword: "Parc" },
  { id: "parking", label: "Parking", googleSearchKeyword: "Parking" },
  { id: "pet_store", label: "Animalerie", googleSearchKeyword: "Animalerie" },
  { id: "pharmacy", label: "Pharmacie", googleSearchKeyword: "Pharmacie" },
  { id: "physiotherapist", label: "Kinésithérapeute", googleSearchKeyword: "Kinésithérapeute" },
  { id: "pizza_restaurant", label: "Pizzeria", googleSearchKeyword: "Pizzeria" },
  { id: "plumber", label: "Plombier", googleSearchKeyword: "Plombier" },
  { id: "preschool", label: "École maternelle", googleSearchKeyword: "École maternelle" },
  { id: "primary_school", label: "École primaire", googleSearchKeyword: "École primaire" },
  { id: "private_guest_room", label: "Chambre privée", googleSearchKeyword: "Chambre privée" },
  { id: "real_estate_agency", label: "Agence immobilière", googleSearchKeyword: "Agence immobilière" },
  { id: "resort_hotel", label: "Hôtel resort", googleSearchKeyword: "Hôtel resort" },
  { id: "restaurant", label: "Restaurant", googleSearchKeyword: "Restaurant" },
  { id: "roofing_contractor", label: "Couvreur", googleSearchKeyword: "Couvreur" },
  { id: "rv_park", label: "Parc pour camping-cars", googleSearchKeyword: "Parc pour camping-cars" },
  { id: "sandwich_shop", label: "Sandwicherie", googleSearchKeyword: "Sandwicherie" },
  { id: "seafood_restaurant", label: "Restaurant de fruits de mer", googleSearchKeyword: "Restaurant de fruits de mer" },
  { id: "secondary_school", label: "Collège", googleSearchKeyword: "Collège" },
  { id: "shoe_store", label: "Magasin de chaussures", googleSearchKeyword: "Magasin de chaussures" },
  { id: "shopping_mall", label: "Centre commercial", googleSearchKeyword: "Centre commercial" },
  { id: "spa", label: "Spa", googleSearchKeyword: "Spa" },
  { id: "spanish_restaurant", label: "Restaurant espagnol", googleSearchKeyword: "Restaurant espagnol" },
  { id: "sporting_goods_store", label: "Magasin d'articles de sport", googleSearchKeyword: "Magasin d'articles de sport" },
  { id: "sports_club", label: "Club de sport", googleSearchKeyword: "Club de sport" },
  { id: "sports_complex", label: "Complexe sportif", googleSearchKeyword: "Complexe sportif" },
  { id: "stadium", label: "Stade", googleSearchKeyword: "Stade" },
  { id: "steak_house", label: "Steakhouse", googleSearchKeyword: "Steakhouse" },
  { id: "storage", label: "Garde-meuble", googleSearchKeyword: "Garde-meuble" },
  { id: "store", label: "Magasin", googleSearchKeyword: "Magasin" },
  { id: "supermarket", label: "Supermarché", googleSearchKeyword: "Supermarché" },
  { id: "sushi_restaurant", label: "Restaurant sushi", googleSearchKeyword: "Restaurant sushi" },
  { id: "swimming_pool", label: "Piscine", googleSearchKeyword: "Piscine" },
  { id: "tailor", label: "Tailleur", googleSearchKeyword: "Tailleur" },
  { id: "tax_consultant", label: "Consultant fiscal", googleSearchKeyword: "Consultant fiscal" },
  { id: "taxi_stand", label: "Station de taxi", googleSearchKeyword: "Station de taxi" },
  { id: "thai_restaurant", label: "Restaurant thaïlandais", googleSearchKeyword: "Restaurant thaïlandais" },
  { id: "tourist_attraction", label: "Attraction touristique", googleSearchKeyword: "Attraction touristique" },
  { id: "travel_agency", label: "Agence de voyage", googleSearchKeyword: "Agence de voyage" },
  { id: "truck_dealer", label: "Concessionnaire de camions", googleSearchKeyword: "Concessionnaire de camions" },
  { id: "truck_repair_shop", label: "Garage poids lourds", googleSearchKeyword: "Garage poids lourds" },
  { id: "turkish_restaurant", label: "Restaurant turc", googleSearchKeyword: "Restaurant turc" },
  { id: "university", label: "Université", googleSearchKeyword: "Université" },
  { id: "used_car_dealer", label: "Concessionnaire voitures d'occasion", googleSearchKeyword: "Concessionnaire voitures d'occasion" },
  { id: "vegan_restaurant", label: "Restaurant vegan", googleSearchKeyword: "Restaurant vegan" },
  { id: "vegetarian_restaurant", label: "Restaurant végétarien", googleSearchKeyword: "Restaurant végétarien" },
  { id: "veterinary_care", label: "Vétérinaire", googleSearchKeyword: "Vétérinaire" },
  { id: "vietnamese_restaurant", label: "Restaurant vietnamien", googleSearchKeyword: "Restaurant vietnamien" },
  { id: "visitor_center", label: "Centre d'accueil", googleSearchKeyword: "Centre d'accueil" },
  { id: "wedding_venue", label: "Lieu de mariage", googleSearchKeyword: "Lieu de mariage" },
  { id: "wholesaler", label: "Grossiste", googleSearchKeyword: "Grossiste" },
  { id: "zoo", label: "Zoo", googleSearchKeyword: "Zoo" },
];
