export interface TypeMapping {
  googleType: string;
  frenchLabel: string;
  weight: number; // Plus le poids est élevé, plus le type est prioritaire
}

export const GOOGLE_TYPES_MAPPING: TypeMapping[] = [
  // Santé et services médicaux
  { googleType: 'physiotherapist', frenchLabel: 'Kinésithérapeute', weight: 10 },
  { googleType: 'doctor', frenchLabel: 'Médecin généraliste', weight: 10 },
  { googleType: 'dentist', frenchLabel: 'Dentiste', weight: 10 },
  { googleType: 'hospital', frenchLabel: 'Hôpital', weight: 9 },
  { googleType: 'pharmacy', frenchLabel: 'Pharmacie', weight: 10 },
  { googleType: 'veterinary_care', frenchLabel: 'Vétérinaire', weight: 10 },
  { googleType: 'medical_lab', frenchLabel: 'Laboratoire médical', weight: 9 },
  { googleType: 'optician', frenchLabel: 'Opticien', weight: 10 },
  { googleType: 'psychologist', frenchLabel: 'Psychologue', weight: 10 },
  { googleType: 'psychiatrist', frenchLabel: 'Psychiatre', weight: 10 },
  { googleType: 'orthoptist', frenchLabel: 'Orthoptiste', weight: 10 },
  { googleType: 'osteopath', frenchLabel: 'Ostéopathe', weight: 10 },
  { googleType: 'chiropractor', frenchLabel: 'Chiropracteur', weight: 10 },
  { googleType: 'speech_therapist', frenchLabel: 'Orthophoniste', weight: 10 },
  { googleType: 'dietitian', frenchLabel: 'Diététicien', weight: 10 },
  { googleType: 'nutritionist', frenchLabel: 'Nutritionniste', weight: 10 },
  { googleType: 'acupuncturist', frenchLabel: 'Acupuncteur', weight: 9 },
  { googleType: 'midwife', frenchLabel: 'Sage-femme', weight: 10 },
  { googleType: 'nurse', frenchLabel: 'Infirmier', weight: 10 },
  
  // Services juridiques et financiers
  { googleType: 'lawyer', frenchLabel: 'Avocat', weight: 10 },
  { googleType: 'notary_public', frenchLabel: 'Notaire', weight: 10 },
  { googleType: 'accounting', frenchLabel: 'Expert-comptable', weight: 10 },
  { googleType: 'tax_consultant', frenchLabel: 'Conseiller fiscal', weight: 10 },
  { googleType: 'financial_consultant', frenchLabel: 'Conseiller financier', weight: 9 },
  { googleType: 'insurance_agency', frenchLabel: 'Agence d\'assurance', weight: 8 },
  { googleType: 'bank', frenchLabel: 'Banque', weight: 8 },
  { googleType: 'atm', frenchLabel: 'Distributeur automatique', weight: 0 },
  
  // BTP et construction
  { googleType: 'interior_designer', frenchLabel: 'Designer d\'intérieur', weight: 9 },
  { googleType: 'general_contractor', frenchLabel: 'Entreprise de rénovation', weight: 5 },
  { googleType: 'electrician', frenchLabel: 'Électricien', weight: 10 },
  { googleType: 'plumber', frenchLabel: 'Plombier', weight: 10 },
  { googleType: 'hvac_contractor', frenchLabel: 'Installateur CVC', weight: 9 },
  { googleType: 'roofing_contractor', frenchLabel: 'Couvreur', weight: 9 },
  { googleType: 'painter', frenchLabel: 'Peintre en bâtiment', weight: 9 },
  { googleType: 'carpenter', frenchLabel: 'Menuisier', weight: 9 },
  { googleType: 'mason', frenchLabel: 'Maçon', weight: 9 },
  { googleType: 'tiler', frenchLabel: 'Carreleur', weight: 9 },
  { googleType: 'landscaper', frenchLabel: 'Paysagiste', weight: 9 },
  { googleType: 'glazier', frenchLabel: 'Vitrier', weight: 9 },
  { googleType: 'flooring_contractor', frenchLabel: 'Installateur de revêtements de sol', weight: 8 },
  { googleType: 'demolition_contractor', frenchLabel: 'Entreprise de démolition', weight: 8 },
  { googleType: 'scaffolding_rental_service', frenchLabel: 'Location d\'échafaudages', weight: 7 },
  
  // Services à domicile
  { googleType: 'locksmith', frenchLabel: 'Serrurier', weight: 10 },
  { googleType: 'cleaning_service', frenchLabel: 'Service de nettoyage', weight: 8 },
  { googleType: 'pest_control_service', frenchLabel: 'Service de dératisation', weight: 9 },
  { googleType: 'house_cleaning_service', frenchLabel: 'Service de ménage à domicile', weight: 9 },
  { googleType: 'window_cleaning_service', frenchLabel: 'Lavage de vitres', weight: 8 },
  { googleType: 'handyman', frenchLabel: 'Homme toutes mains', weight: 8 },
  { googleType: 'gardener', frenchLabel: 'Jardinier', weight: 9 },
  { googleType: 'tree_service', frenchLabel: 'Élagueur', weight: 9 },
  { googleType: 'moving_company', frenchLabel: 'Déménageur', weight: 9 },
  { googleType: 'storage_facility', frenchLabel: 'Garde-meuble', weight: 8 },
  
  // Commerce et beauté
  { googleType: 'hair_care', frenchLabel: 'Salon de coiffure', weight: 10 },
  { googleType: 'beauty_salon', frenchLabel: 'Institut de beauté', weight: 10 },
  { googleType: 'barber_shop', frenchLabel: 'Salon de coiffure pour hommes', weight: 10 },
  { googleType: 'nail_salon', frenchLabel: 'Salon de manucure', weight: 10 },
  { googleType: 'spa', frenchLabel: 'Spa', weight: 9 },
  { googleType: 'massage', frenchLabel: 'Salon de massage', weight: 9 },
  { googleType: 'tattoo_shop', frenchLabel: 'Salon de tatouage', weight: 9 },
  { googleType: 'tanning_salon', frenchLabel: 'Centre de bronzage', weight: 8 },
  
  // Restauration et alimentation
  { googleType: 'restaurant', frenchLabel: 'Restaurant', weight: 8 },
  { googleType: 'cafe', frenchLabel: 'Café', weight: 8 },
  { googleType: 'bakery', frenchLabel: 'Boulangerie', weight: 10 },
  { googleType: 'pastry_shop', frenchLabel: 'Pâtisserie', weight: 10 },
  { googleType: 'butcher_shop', frenchLabel: 'Boucherie', weight: 10 },
  { googleType: 'seafood_market', frenchLabel: 'Poissonnerie', weight: 10 },
  { googleType: 'grocery_store', frenchLabel: 'Épicerie', weight: 8 },
  { googleType: 'supermarket', frenchLabel: 'Supermarché', weight: 7 },
  { googleType: 'delicatessen', frenchLabel: 'Charcuterie', weight: 9 },
  { googleType: 'cheese_shop', frenchLabel: 'Fromagerie', weight: 10 },
  { googleType: 'wine_shop', frenchLabel: 'Caviste', weight: 9 },
  { googleType: 'liquor_store', frenchLabel: 'Magasin de spiritueux', weight: 8 },
  { googleType: 'pizza_restaurant', frenchLabel: 'Pizzeria', weight: 9 },
  { googleType: 'fast_food_restaurant', frenchLabel: 'Restaurant rapide', weight: 7 },
  { googleType: 'ice_cream_shop', frenchLabel: 'Glacier', weight: 9 },
  { googleType: 'coffee_shop', frenchLabel: 'Coffee shop', weight: 8 },
  { googleType: 'tea_house', frenchLabel: 'Salon de thé', weight: 9 },
  { googleType: 'bar', frenchLabel: 'Bar', weight: 7 },
  { googleType: 'night_club', frenchLabel: 'Boîte de nuit', weight: 8 },
  { googleType: 'catering_service', frenchLabel: 'Service de traiteur', weight: 9 },
  
  // Automobile
  { googleType: 'car_repair', frenchLabel: 'Garage automobile', weight: 9 },
  { googleType: 'auto_body_shop', frenchLabel: 'Carrosserie', weight: 9 },
  { googleType: 'car_wash', frenchLabel: 'Lavage auto', weight: 8 },
  { googleType: 'gas_station', frenchLabel: 'Station-service', weight: 7 },
  { googleType: 'car_dealer', frenchLabel: 'Concessionnaire automobile', weight: 8 },
  { googleType: 'motorcycle_dealer', frenchLabel: 'Concessionnaire moto', weight: 8 },
  { googleType: 'tire_shop', frenchLabel: 'Centre de pneus', weight: 9 },
  { googleType: 'auto_parts_store', frenchLabel: 'Magasin de pièces auto', weight: 8 },
  { googleType: 'towing_service', frenchLabel: 'Service de remorquage', weight: 9 },
  { googleType: 'parking', frenchLabel: 'Parking', weight: 0 },
  
  // Commerce de détail
  { googleType: 'store', frenchLabel: 'Magasin', weight: 3 },
  { googleType: 'clothing_store', frenchLabel: 'Magasin de vêtements', weight: 8 },
  { googleType: 'shoe_store', frenchLabel: 'Magasin de chaussures', weight: 9 },
  { googleType: 'jewelry_store', frenchLabel: 'Bijouterie', weight: 9 },
  { googleType: 'watch_store', frenchLabel: 'Horlogerie', weight: 9 },
  { googleType: 'furniture_store', frenchLabel: 'Magasin de meubles', weight: 8 },
  { googleType: 'home_goods_store', frenchLabel: 'Magasin de décoration', weight: 7 },
  { googleType: 'electronics_store', frenchLabel: 'Magasin d\'électronique', weight: 8 },
  { googleType: 'appliance_store', frenchLabel: 'Magasin d\'électroménager', weight: 8 },
  { googleType: 'hardware_store', frenchLabel: 'Quincaillerie', weight: 8 },
  { googleType: 'paint_store', frenchLabel: 'Magasin de peinture', weight: 8 },
  { googleType: 'florist', frenchLabel: 'Fleuriste', weight: 10 },
  { googleType: 'gift_shop', frenchLabel: 'Boutique de cadeaux', weight: 7 },
  { googleType: 'toy_store', frenchLabel: 'Magasin de jouets', weight: 8 },
  { googleType: 'pet_store', frenchLabel: 'Animalerie', weight: 9 },
  { googleType: 'book_store', frenchLabel: 'Librairie', weight: 9 },
  { googleType: 'sporting_goods_store', frenchLabel: 'Magasin de sport', weight: 8 },
  { googleType: 'bicycle_store', frenchLabel: 'Magasin de vélos', weight: 9 },
  { googleType: 'camping_store', frenchLabel: 'Magasin de camping', weight: 8 },
  { googleType: 'hunting_store', frenchLabel: 'Magasin de chasse', weight: 8 },
  { googleType: 'fishing_store', frenchLabel: 'Magasin de pêche', weight: 8 },
  { googleType: 'outdoor_sports_store', frenchLabel: 'Magasin de sports outdoor', weight: 8 },
  { googleType: 'luggage_store', frenchLabel: 'Magasin de bagages', weight: 8 },
  { googleType: 'department_store', frenchLabel: 'Grand magasin', weight: 6 },
  { googleType: 'shopping_mall', frenchLabel: 'Centre commercial', weight: 5 },
  { googleType: 'convenience_store', frenchLabel: 'Supérette', weight: 7 },
  
  // Services professionnels
  { googleType: 'real_estate_agency', frenchLabel: 'Agence immobilière', weight: 9 },
  { googleType: 'travel_agency', frenchLabel: 'Agence de voyage', weight: 9 },
  { googleType: 'employment_agency', frenchLabel: 'Agence d\'intérim', weight: 9 },
  { googleType: 'marketing_agency', frenchLabel: 'Agence de marketing', weight: 8 },
  { googleType: 'advertising_agency', frenchLabel: 'Agence de publicité', weight: 8 },
  { googleType: 'web_design', frenchLabel: 'Agence web', weight: 9 },
  { googleType: 'graphic_designer', frenchLabel: 'Graphiste', weight: 9 },
  { googleType: 'photographer', frenchLabel: 'Photographe', weight: 9 },
  { googleType: 'videographer', frenchLabel: 'Vidéaste', weight: 9 },
  { googleType: 'printing_service', frenchLabel: 'Imprimerie', weight: 8 },
  { googleType: 'copy_shop', frenchLabel: 'Centre de reprographie', weight: 8 },
  { googleType: 'translator', frenchLabel: 'Traducteur', weight: 9 },
  { googleType: 'courier_service', frenchLabel: 'Service de coursier', weight: 8 },
  { googleType: 'shipping_service', frenchLabel: 'Service d\'expédition', weight: 8 },
  
  // Éducation et formation
  { googleType: 'school', frenchLabel: 'École', weight: 7 },
  { googleType: 'preschool', frenchLabel: 'École maternelle', weight: 8 },
  { googleType: 'primary_school', frenchLabel: 'École primaire', weight: 8 },
  { googleType: 'secondary_school', frenchLabel: 'Collège', weight: 8 },
  { googleType: 'high_school', frenchLabel: 'Lycée', weight: 8 },
  { googleType: 'university', frenchLabel: 'Université', weight: 8 },
  { googleType: 'driving_school', frenchLabel: 'Auto-école', weight: 10 },
  { googleType: 'language_school', frenchLabel: 'École de langues', weight: 9 },
  { googleType: 'music_school', frenchLabel: 'École de musique', weight: 9 },
  { googleType: 'dance_school', frenchLabel: 'École de danse', weight: 9 },
  { googleType: 'art_school', frenchLabel: 'École d\'art', weight: 9 },
  { googleType: 'cooking_school', frenchLabel: 'École de cuisine', weight: 9 },
  { googleType: 'tutoring_service', frenchLabel: 'Soutien scolaire', weight: 9 },
  
  // Sport et loisirs
  { googleType: 'gym', frenchLabel: 'Salle de sport', weight: 9 },
  { googleType: 'fitness_center', frenchLabel: 'Centre de fitness', weight: 9 },
  { googleType: 'yoga_studio', frenchLabel: 'Studio de yoga', weight: 9 },
  { googleType: 'pilates_studio', frenchLabel: 'Studio de Pilates', weight: 9 },
  { googleType: 'martial_arts_school', frenchLabel: 'École d\'arts martiaux', weight: 9 },
  { googleType: 'swimming_pool', frenchLabel: 'Piscine', weight: 8 },
  { googleType: 'sports_club', frenchLabel: 'Club de sport', weight: 8 },
  { googleType: 'golf_course', frenchLabel: 'Golf', weight: 8 },
  { googleType: 'tennis_court', frenchLabel: 'Court de tennis', weight: 8 },
  { googleType: 'stadium', frenchLabel: 'Stade', weight: 7 },
  { googleType: 'bowling_alley', frenchLabel: 'Bowling', weight: 8 },
  { googleType: 'movie_theater', frenchLabel: 'Cinéma', weight: 8 },
  { googleType: 'amusement_park', frenchLabel: 'Parc d\'attractions', weight: 8 },
  { googleType: 'aquarium', frenchLabel: 'Aquarium', weight: 8 },
  { googleType: 'zoo', frenchLabel: 'Zoo', weight: 8 },
  { googleType: 'museum', frenchLabel: 'Musée', weight: 8 },
  { googleType: 'art_gallery', frenchLabel: 'Galerie d\'art', weight: 8 },
  { googleType: 'library', frenchLabel: 'Bibliothèque', weight: 7 },
  
  // Hébergement et tourisme
  { googleType: 'hotel', frenchLabel: 'Hôtel', weight: 8 },
  { googleType: 'motel', frenchLabel: 'Motel', weight: 8 },
  { googleType: 'bed_and_breakfast', frenchLabel: 'Chambre d\'hôtes', weight: 9 },
  { googleType: 'guest_house', frenchLabel: 'Maison d\'hôtes', weight: 9 },
  { googleType: 'hostel', frenchLabel: 'Auberge de jeunesse', weight: 8 },
  { googleType: 'campground', frenchLabel: 'Camping', weight: 8 },
  { googleType: 'rv_park', frenchLabel: 'Camping-car', weight: 7 },
  { googleType: 'vacation_rental', frenchLabel: 'Location de vacances', weight: 8 },
  
  // Services publics et administration
  { googleType: 'post_office', frenchLabel: 'Bureau de poste', weight: 8 },
  { googleType: 'city_hall', frenchLabel: 'Mairie', weight: 8 },
  { googleType: 'police', frenchLabel: 'Commissariat de police', weight: 8 },
  { googleType: 'fire_station', frenchLabel: 'Caserne de pompiers', weight: 8 },
  { googleType: 'courthouse', frenchLabel: 'Tribunal', weight: 8 },
  { googleType: 'embassy', frenchLabel: 'Ambassade', weight: 8 },
  { googleType: 'consulate', frenchLabel: 'Consulat', weight: 8 },
  
  // Religion
  { googleType: 'church', frenchLabel: 'Église', weight: 7 },
  { googleType: 'mosque', frenchLabel: 'Mosquée', weight: 8 },
  { googleType: 'synagogue', frenchLabel: 'Synagogue', weight: 8 },
  { googleType: 'hindu_temple', frenchLabel: 'Temple hindou', weight: 8 },
  { googleType: 'buddhist_temple', frenchLabel: 'Temple bouddhiste', weight: 8 },
  { googleType: 'cemetery', frenchLabel: 'Cimetière', weight: 6 },
  { googleType: 'funeral_home', frenchLabel: 'Pompes funèbres', weight: 9 },
  
  // Types génériques (poids très faible)
  { googleType: 'point_of_interest', frenchLabel: 'Point d\'intérêt', weight: 0 },
  { googleType: 'establishment', frenchLabel: 'Établissement', weight: 0 },
  { googleType: 'premise', frenchLabel: 'Lieu', weight: 0 },
  { googleType: 'subpremise', frenchLabel: 'Sous-lieu', weight: 0 },
  { googleType: 'natural_feature', frenchLabel: 'Élément naturel', weight: 0 },
  { googleType: 'locality', frenchLabel: 'Localité', weight: 0 },
  { googleType: 'political', frenchLabel: 'Zone administrative', weight: 0 },
];

// Créer un index pour une recherche rapide
export const GOOGLE_TYPES_MAP = GOOGLE_TYPES_MAPPING.reduce((acc, mapping) => {
  acc[mapping.googleType] = mapping;
  return acc;
}, {} as Record<string, TypeMapping>);
